platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "alpine"

inputs:
- name: demo1Spring

outputs:
- name: built-project

run:
  path: sh
  args:
  - -exc
  - |
    cd demo1Spring
    mvn package
    cp ./target/demo-0.0.1-SNAPSHOT.jar ../built-project/demo.jar
